// USER
export const SET_USER = 'SET_USER'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const LOADING_USER = 'LOADING_USER'

// UI
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'

// DATA
export const SET_SCREAMS = 'SET_SCREAMS'
export const LOADING_DATA = 'LOADING_DATA'
export const LIKE_SCREAM = 'LIKE_SCREAM'
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM'
export const DELETE_SCREAM = 'DELETE_SCREAM'
export const ADD_SCREAM = 'ADD_SCREAM'
export const SET_SCREAM = 'SET_SCREAM'
export const COMMENT_SCREAM = 'COMMENT_SCREAM'
export const LOADING_COMMENT = 'LOADING_COMMENT'
export const STOP_LOADING_COMMENT = 'STOP_LOADING_COMMENT'